
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "cercetatori/*.qmd"

website:
  title: "Compas Social România"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Acasă
      - href: proiecte.qmd
        text: Proiect Rădăcini
      - href: publicatii.qmd
        text: Publicații
      - href: cercetatori.qmd
        text: Cercetători
      - href: mass-media.qmd
        text: Mass-media
      - href: opinii.qmd
        text: Opinii
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    lang: ro
    page-layout: full