---
title: "Cercetători"
---

## Filip Alexandrescu

Filip Alexandrescu este doctor în sociologie al Universității Toronto și cercetător științific la Institutul de Cercetare a Calității Vieții al Academiei Române.

**Interese de cercetare:**

- marginalizare socială
- rasism spațial
- mediu și schimbări climatice
- neoliberalism urban

## Ionuț-Marian Anghel

Ionuț-Marian Anghel este sociolog și cercetător științific la Institutul de Cercetare a Calității Vieții. Doctor în sociologie al Școlii de Studii Avansate a Academiei Române, preocupările sale de cercetare vizează politicile sociale, inegalitățile, transformările statului social și guvernanța minorităților etnice în Europa post-socialistă.

**Interese de cercetare:**

- politici publice
- inegalități sociale
- migrație
- marginalitate urbană
- mișcări sociale

## Alina Pop

Alina Pop a obținut titlul de doctor de la Universitatea Sapienza din Roma. Interesele sale recente vizează marginalizarea socială, rolul femeilor în guvernarea locală și imigrația.

**Interese de cercetare:**

- reprezentări sociale
- guvernare locală
- imigrație pentru muncă
- marginalitate urbană
