---
title: "Publicații"
---

## Cărți

- [*Suveranismul în România. De ce votează oamenii cu politicieni extremiști?*](https://humanitas.ro/humanitas/carte/suveranismul-in-romania)

## Articole

- Pop, Alina, Filip Alexandrescu, Júlia Adorjáni, and Ionuț Marian Anghel. 2025. „Feminisation, Governance and Roma on the Urban Margins.” *The Sociological Review*. [DOI](https://doi.org/10.1177/00380261251337281)
- Anghel, Ionuț Marian. 2025. „Examining the expansion of social protection measures in EU countries during the Covid-19 pandemic crisis. What was different this time?” *International Journal of Sociology and Social Policy*. [DOI](https://doi.org/10.1108/IJSSP-01-2025-0069)
- Anghel, Ionuț Marian, and Filip Alexandrescu. 2025. „(Post)socialist urban orders and the unsettlement of racialized Roma in Romania.” *Eurasian Geography and Economics*. [DOI](https://doi.org/10.1080/15387216.2025.2521022)
- Rusu, O., F. Alexandrescu, I. Bunescu, I. Codreanu, C. Gheorghe, and I. Velicu. 2026. „Insidious Whiteness in Eastern Europe: Environmental Injustice and Dehumanisation in a Roma Community.” *Antipode*. [DOI](https://doi.org/10.1111/anti.70170)
- Alexandrescu, Filip, Lucrina Ștefănescu, and Alina Pop. 2026. „Hotbeds of climate vulnerability: marginalization, informality, and invisibilization of Roma slums in Romania.” *Eurasian Geography and Economics*. [DOI](https://doi.org/10.1080/15387216.2024.2418323)

## Rapoarte

Aici vor fi adăugate rapoartele de cercetare.
